OddamWDobreRece/OddamWDobreRece/urls.py
from django.contrib import admin
from django.urls import path

from MainSite.views import LandingPageView, LoginView, RegisterView, AddDonationView, LogoutView, UserView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name = 'index'),
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('register/', RegisterView.as_view(), name = 'register'),
    path('donate/', AddDonationView.as_view(), name = 'donate'),
    path('user/', UserView.as_view(), name='user-view')
]

OddamWDobreRece/MainSite/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

INSTITUTION_TYPE = (
    ('fundation', 'fundacja'),
    ('ngo', 'organizacja pozarządowa'),
    ('lokal', 'zbiórka lokalna'),
)

class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    type = models.CharField(choices=INSTITUTION_TYPE, default='fundation')
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='institution_donations')
    address = models.CharField(max_length=128)
    phone_number = models.CharField(max_length=20)
    donation_city = models.CharField(max_length=64)
    zip_code = models.IntegerField()
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.CharField(max_length=256, blank=True, null=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

OddamWDobreRece/MainSite/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from .models import Donation


class AddUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Potwierdź hasło", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if password != password_confirm:
            raise ValidationError("Hasła nie pasują do siebie. Upewnij się, że wprowadzone hasła są takie same.")
        return cleaned_data
    

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('email')
        password = cleaned_data.get('password')
        self.user = authenticate(username=username, password=password)
        if self.user is None:
            raise ValidationError("Wrong login or pass")
        

class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ['quantity',
                  'institution',
                  'address',
                  'phone_number',
                  'donation_city', 
                  'zip_code',
                  'pick_up_date',
                  'pick_up_time',
                  'pick_up_comment',
                  'user']

OddamWDobreRece/MainSite/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import FormView
from django.views.generic import RedirectView
from django.db.models import Sum
from django.db.models import Count
from django.contrib.auth import login, logout

from django.contrib.auth.models import User

from MainSite.forms import AddUserForm, DonationForm, LoginForm

from .models import Donation, Institution, Category


class LandingPageView(View):
    def get(self, request, *args, **kwargs):
        bags_count = Donation.objects.aggregate(bags_count=Sum('quantity'))['bags_count']
        if bags_count == None:
            bags_count = 0


        institutions_with_donations = Donation.objects.all().distinct('institution').count()

        institutions = Institution.objects.all()
        context = {
            'bags_count': bags_count,
            'institutions_with_donations': institutions_with_donations,
            'institutions': institutions
        }
        
        return render(request, "MainSite/index.html", context)

    
class LoginView(FormView):
    template_name = "MainSite/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("index")
    register_url = reverse_lazy("register")

    def form_valid(self, form):
        user = form.user
        
        login(self.request, user)
        
        return super().form_valid(form) 

    def form_invalid(self, form):
        email = form.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            return redirect(self.register_url)
        return super().form_invalid(form)


class LogoutView(RedirectView):
    url = reverse_lazy('index')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class RegisterView(View):
    form_class = AddUserForm
    template_name = "MainSite/register.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        print("get")
        context = {"form": form}
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        context = {"form": form}

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.email
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('login')
        else:
            return render(request, self.template_name, context)


# class AddDonationView(View):
#     def get(self, request, *args, **kwargs):
#         donation_categories = Category.objects.all()
#         institutions = Institution.objects.all()
#         context = {
#             'donation_categories': donation_categories,
#             'institutions': institutions
#         }
#         return render(request, "MainSite/form.html", context)
    

class AddDonationView(View):
    form_class = DonationForm
    template_name = "MainSite/form.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        donation_categories = Category.objects.all()
        institutions = Institution.objects.all()
        context = {
            'donation_categories': donation_categories,
            'institutions': institutions,
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        donation_categories = Category.objects.all()
        institutions = Institution.objects.all()
        context = {
            'donation_categories': donation_categories,
            'institutions': institutions,
            'form': form
        }

        if form.is_valid():
            donation = form.save()
            return redirect('index')
        else:
            # Wyświetlenie błędów formularza w terminalu
            print('Formularz nieprawidłowy. Błędy:')
        for field, errors in form.errors.items():
            for error in errors:
                print(f'{field}: {error}')

        return render(request, self.template_name, context)
    

class UserView(View):
    def get(self, request, *args, **kwargs):

        total_bags = Donation.objects.filter(user=request.user).aggregate(total_bags=Count('quantity'))['total_bags']
        total_institutions = Donation.objects.filter(user=request.user).values('institution').distinct().count()

        user = User.objects.get(pk=request.user.pk)
        user_donations = Donation.objects.filter(user=user.pk)
        print(user)
        print(user_donations)
        
        context = {
            'total_bags': total_bags,
            'total_institutions': total_institutions,
            'donations': user_donations
        }
        return render(request, "MainSite/user-site.html", context)

OddamWDobreRece/MainSite/templates/MainSite/base.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Oddam W Dobre Ręce</title>
    <link rel="stylesheet" type="text/css" href="{% static 'MainSite/css/style.css' %}">
</head>
<body>
    {% block content %}{% endblock %}
    <footer>
        <div id="contact" class="contact">
          <h2>Skontaktuj się z nami</h2>
          <h3>Formularz kontaktowy</h3>
          <form class="form--contact">
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>
    
            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>
    
            <button class="btn" type="submit">Wyślij</button>
          </form>
        </div>
        <div class="bottom-line">
          <span class="bottom-line--copy">Copyright &copy; 2019</span>
          <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="{% static 'MainSite/images/icon-facebook.svg' %}"/></a>
            <a href="#" class="btn btn--small"><img src="{% static 'MainSite/images/icon-instagram.svg' %}"/></a>
          </div>
        </div>
      </footer>
      <script src="{% static 'MainSite/js/app.js' %}"></script>
</body>
</html>

OddamWDobreRece/MainSite/templates/MainSite/includes/header.html
<nav class="container container--70"  id="start">
  {% if user.is_authenticated %}
    <div class="nav--actions">
      <div class="nav--dropdown">
        <span class="btn btn--small btn--without-border">Witaj, {{ user.first_name }}</span>
        <div class="nav--dropdown-content" > 
            <p><a href="{% url 'user-view' %}">Profil</a></p>
            <p><a href="{% url 'index' %}">Ustawienia</a></p>
            <p><a href="{% url 'logout' %}">Wyloguj</a></p>
        </div>
      </div>
    </div>
  {% else %}
  
    <ul class="nav--actions">
      <li><a href="{% url 'login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
      <li><a href="{% url 'register' %}#register-section" class="btn btn--small btn--highlighted">Załóż konto</a></li>
    </ul>
  {% endif %}
    <ul>
      <li><a href="/#start" class="btn btn--without-border active">Start</a></li>
      <li><a href="/#steps" class="btn btn--without-border">O co chodzi?</a></li>
      <li><a href="/#about-us" class="btn btn--without-border">O nas</a></li>
      <li><a href="/#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
    {% if user.is_authenticated %}
      <li><a href="{% url 'donate' %}" class="btn btn--without-border">Przekaż dary</a></li>
    {% else %}
      <li><a href="{% url 'login' %}" class="btn btn--without-border">Przekaż dary</a></li>
    {% endif %}
      <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
    </ul>
  </nav>
  

OddamWDobreRece/MainSite/templates/MainSite/index.html
{% extends 'MainSite/base.html' %}
{% load static %}

{% block content %}
<header class="header--main-page">
  {% include 'MainSite/includes/header.html' %} 
  <div class="slogan container container--90">
    <div class="slogan--item">
      <h1>
        Zacznij pomagać!<br />
        Oddaj niechciane rzeczy w zaufane ręce
      </h1>
    </div>
</div>
</header>

<section id="stats" class="stats">
  <div class="container container--85">
    <div class="stats--item">
      <em>{{ bags_count }}</em>
      <h3>Oddanych worków</h3>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
    </div>

    <div class="stats--item">
      <em>{{institutions_with_donations }}</em>
      <h3>Wspartych organizacji</h3>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
    </div>

  </div>
</section>

<section id="steps" class="steps">
  <h2>Wystarczą 4 proste kroki</h2>

  <div class="steps--container">
    <div class="steps--item">
      <span class="icon icon--hands"></span>
      <h3>Wybierz rzeczy</h3>
      <p>ubrania, zabawki, sprzęt i inne</p>
    </div>
    <div class="steps--item">
      <span class="icon icon--arrow"></span>
      <h3>Spakuj je</h3>
      <p>skorzystaj z worków na śmieci</p>
    </div>
    <div class="steps--item">
      <span class="icon icon--glasses"></span>
      <h3>Zdecyduj komu chcesz pomóc</h3>
      <p>wybierz zaufane miejsce</p>
    </div>
    <div class="steps--item">
      <span class="icon icon--courier"></span>
      <h3>Zamów kuriera</h3>
      <p>kurier przyjedzie w dogodnym terminie</p>
    </div>
  </div>

  <a href="{% url 'register' %}" class="btn btn--large">Załóż konto</a>
</section>

<section id="about-us" class="about-us">
  <div class="about-us--text">
    <h2>O nas</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
    <img src="images/signature.svg" class="about-us--text-signature" alt="Signature" />
  </div>
  <div class="about-us--image"><img src="images/about-us.jpg" alt="People in circle" /></div>
</section>


<section id="help" class="help">
  <h2>Komu pomagamy?</h2>

  <ul class="help--buttons">
    <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
    <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
    <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
  </ul>
  
  <!-- SLIDE 1 -->
  <div class="help--slides active" data-id="1">
    <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>
    {% for institution in institutions %}      
      <ul class="help--slides-items">
          {%if institution.type == 'fundation'%}
            <li>
              <div class="col">
                <div class="title">{{ institution.name }}</div>
                <div class="subtitle">{{ institution.description }}</div>
              </div>
              
              <div class="col">
                <div class="text">
                  {% for category in institution.categories.all %}
                    {{ category }}
                    {% if not forloop.last %},{% endif %}
                  {% endfor %}
                </div>
              </div>
              
            </li>
          {% endif %}
      </ul>
    {% endfor %}
    
    <!-- Pagination
    <ul class="help--slides-pagination">
      <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
      <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
      <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
    </ul>
    -->
  </div>



  <!-- SLIDE 2 -->
  <div class="help--slides" data-id="2">
    <p>
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
      quos suscipit corporis!
    </p>
    {% for institution in institutions %}      
      <ul class="help--slides-items">
          {%if institution.type == 'ngo'%}
            <li>
              <div class="col">
                <div class="title">{{ institution.name }}</div>
                <div class="subtitle">{{ institution.description }}</div>
              </div>
              
              <div class="col">
                <div class="text">
                  {% for category in institution.categories.all %}
                    {{ category }}
                    {% if not forloop.last %},{% endif %}
                  {% endfor %}
                </div>
              </div>
              
            </li>
          {% endif %}
      </ul>
    {% endfor %}

    <!-- Pagination
    <ul class="help--slides-pagination">
      <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
      <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
      <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
      <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
      <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
    </ul>
    -->
  </div>

  <!-- SLIDE 3 -->
  <div class="help--slides" data-id="3">
    <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
    {% for institution in institutions %}      
      <ul class="help--slides-items">
          {%if institution.type == 'lokal'%}
            <li>
              <div class="col">
                <div class="title">{{ institution.name }}</div>
                <div class="subtitle">{{ institution.description }}</div>
              </div>
              
              <div class="col">
                <div class="text">
                  {% for category in institution.categories.all %}
                    {{ category }}
                    {% if not forloop.last %},{% endif %}
                  {% endfor %}
                </div>
              </div>
              
            </li>
          {% endif %}
      </ul>
    {% endfor %}

    <!-- Pagination
    <ul class="help--slides-pagination">
      <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
      <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
    </ul>
    -->
  </div>                
</section>



{% comment %} <script src="{% static 'MainSite/js/app.js' %}"></script> {% endcomment %}
{% endblock %}

OddamWDobreRece/MainSite/templates/MainSite/login.html
{% extends 'MainSite/base.html' %}
{% load static %}

{% block content %}
  <header>
    {% include 'MainSite/includes/header.html' %} 
  </header>
  <section class="login-page">
    <h2>Zaloguj się</h2>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <input id="id_email" type="email" name="email" placeholder="Email" />
      </div>
      <div class="form-group">
        <input id="id_password" type="password" name="password" placeholder="Hasło" />
        <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
      </div>

      <div class="form-group form-group--buttons">
        <a href="#" class="btn btn--without-border">Załóż konto</a>      
        <button class="btn" type="submit">Zaloguj się</button> 
      </div>
    </form>
  </section>
{% endblock %}

OddamWDobreRece/MainSite/templates/MainSite/register.html
{% extends 'MainSite/base.html' %}
{% load static %}

{% block content %}
<header>
  {% include 'MainSite/includes/header.html' %} 
</header>
  {% comment %} {{form}} {% endcomment %}
    <section class="login-page">
      <h2  id="register-section">Załóż konto</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <input id="id_first_name" type="text" name="first_name" placeholder="Imię" />
        </div>
         <div class="form-group">
          <input id="id_last_name" type="text" name="last_name" placeholder="Nazwisko" />
        </div>
        <div class="form-group">
          <input id="id_email" type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input id="id_password" type="password" name="password" placeholder="Hasło" />
        </div>
        <div class="form-group">
          <input id="id_password_confirm" type="password" name="password_confirm" placeholder="Powtórz hasło" />
        </div>

        <div class="form-group form-group--buttons">
          <a href="login.html" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>
{% endblock %}

OddamWDobreRece/MainSite/templates/MainSite/user-site.html
{% extends 'MainSite/base.html' %}
{% load static %}

{% block content %}
  <header>
    {% include 'MainSite/includes/header.html' %} 
  </header>
  <div style="text-align: center;">
    <div class="help">
      <h2 style="margin-bottom: 20px;">Dane użytkownika</h2>
      <p><strong>Imię:</strong> {{ user.first_name }}</p>
      <p><strong>Nazwisko:</strong> {{ user.last_name }}</p>
      <p><strong>Email:</strong> {{ user.email }}</p>
    </div>
  </div>

  <section id="stats" class="stats">
    <div class="container container--85">
      <div class="stats--item">
        <em>{{ total_bags }}</em>
        <h3>Oddanych przez Ciebie worków</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
      </div>
  
      <div class="stats--item">
        <em>{{total_institutions }}</em>
        <h3>Wspartych przez Ciebie organizacji</h3>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
      </div>
    </div>
  </section>

  <h2>Wsparłeś:</h2>
    <ul class="donation-list--user-site">
        {% for donation in donations %}
        <li class="donation-item--user-site">
            <strong>Organizacja:</strong> {{ donation.institution }}<br>
            <strong>Liczba worków:</strong> {{ donation.quantity }}<br>
            <strong>Kategorie:</strong> {{ donation.categories.all|join:", " }}<br>
            <strong>Data odbioru:</strong> {{ donation.pick_up_date }}
        </li>
        {% endfor %}
    </ul>

  
  {% comment %} <section class="login-page">
    <h2>Zaloguj się</h2>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <input id="id_email" type="email" name="email" placeholder="Email" />
      </div>
      <div class="form-group">
        <input id="id_password" type="password" name="password" placeholder="Hasło" />
        <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
      </div>

      <div class="form-group form-group--buttons">
        <a href="#" class="btn btn--without-border">Załóż konto</a>      
        <button class="btn" type="submit">Zaloguj się</button> 
      </div>
    </form>
  </section> {% endcomment %}
{% endblock %}